export interface Item {
    barcodeprice: number;
    barcodeweight: number;
    posadditem: boolean;
    loyaltypoints: number;
    calculateloyaltyfrom: number;
    giftvoucher: boolean;
    intrastatexcluded: boolean;
    createcustomerproductincustomerpark: boolean;
    ismaintenancecontract: boolean;
    isguaranteeextension: boolean;
    customerparkcreation: number;
    stockbookingallowed: boolean;
    automaticstockbooking: boolean;
    includetorecursivereplenishment: boolean;
    includetofabricationreplenishment: boolean;
    includetosupplierreplenishment: boolean;
    cadencequantity: number;
    cadencenumberofdays: number;
    donotassortassemblyrequestswithdifferentdates: boolean;
    maximumgapdaytoassort: number;
    nomenclatureaccountingtransfertypeforsale: number;
    nomenclatureaccountingtransfertypeforpurchase: number;
    virtualpump: boolean;
    virtualstockvalue: number;
    bookedquantity: number;
    purchasebillofquantitiesprogram_keepactivefromquotetoorder: boolean;
    notonmarket: boolean;
    purchaseunitpriceprogram_keepactivefromquotetoorder: boolean;
    canbepartiallydelivered: boolean;
    caption: string;
    oxatis_oxatis_handlingsurcharge1st: number;
    oxatis_oxatis_handlingsurchargeothers: number;
    interventiondurationequalsquantity: boolean;
    height: number;
    width: number;
    length: number;
    oxatis_oxatis_usesubfamilyasbrand: boolean;
    ismanagedbycountermark: boolean;
    iscountermarkforced: boolean;
    salepurchaseconversionrate: number;
    limitdatemode: number;
    limitdatesafetydelay: number;
    uniqueid: string;
    purchaseprice: number;
    chargerate: number;
    chargeamount: number;
    costprice: number;
    interestrate: number;
    interestamount: number;
    salepricevatexcluded: number;
    brandrate: number;
    vatamount: number;
    salepricevatincluded: number;
    managestock: boolean;
    realstock: number;
    pump: number;
    stockvalue: number;
    orderedquantity: number;
    suppliersorderedquantity: number;
    virtualstock: number;
    defaultquantity: number;
    volume: number;
    weight: number;
    netweight: number;
    componentspurchaseprice: number;
    componentscostprice: number;
    componentssalepricevatexcluded: number;
    componentssalepricevatincluded: number;
    printcomponentdetail: number;
    assemblingvirtualquantity: number;
    disassemblingquantity: number;
    quantityusedtoassemblate: number;
    quantityfromdisassembling: number;
    allownegativestock: boolean;
    usecomponentvat: boolean;
    applypricelistoncomponents: boolean;
    activestate: number;
    advisedsalepricevatexcluded: number;
    setitemsalepricewithadvisedsaleprice: boolean;
    trackingmode: number;
    allowcomponentsmodification: boolean;
    allowpublishonweb: boolean;
    imageversion: number;
    pricedecimalnumber: number;
    ishumanservicesincludedinattestation: boolean;
    oxatis_oxatis_showinstocknote: boolean;
    oxatis_oxatis_showstocklevel: boolean;
    oxatis_oxatis_showifoutofstock: boolean;
    oxatis_oxatis_saleifoutofstock: boolean;
    oxatis_oxatis_saleifoutofstockscenario: number;
    oxatis_oxatis_showdaystoship: boolean;
    oxatis_oxatis_shipprice: number;
    oxatis_oxatis_daystoship: number;
    oxatis_oxatis_usermainsupplierdaystoship: boolean;
    id: string;
    itemtype: number;
    billofquantitiesprogram_keepactivefromquotetoorder: boolean;
    saleunitpriceprogram_keepactivefromquotetoorder: boolean;
    updatecomponentsstockinfabrication: boolean;
    customersdeliveryorderpreparingquantity: number;
    customersreturnorderpreparingquantity: number;
    suppliersdeliveryorderpreparingquantity: number;
    suppliersreturnorderpreparingquantity: number;
    stockbillofquantitiesprogram_keepactivefromquotetoorder: boolean;
    purchasechargesrate: number;
    posisscale: boolean;
    postare: string | null;
    updatecomponentsstockinfabrication: boolean;
    customersdeliveryorderpreparingquantity: number;
    customersreturnorderpreparingquantity: number;
    suppliersdeliveryorderpreparingquantity: number;
    suppliersreturnorderpreparingquantity: number;
    stockbillofquantitiesprogram_keepactivefromquotetoorder: boolean;
    purchasechargesrate: number;
    posisscale: boolean;
    postare: string | null;
    billofquantitiesprogram_program: string | null;
    replenishmentdeliveryaddresstype: number;
    saleunitpriceprogram_program: string | null;
    descom: string;
    descomclear: string;
    itemimage: string | null;
    barcode: string | null;
    unitid: string | null;
    familyid: string | null;
    subfamilyid: string | null;
    syscreateddate: string;
    syscreateduser: string;
    sysmodifieddate: string;
    sysmodifieduser: string;
    notesclear: string | null;
    notes: string | null;
    oxatis_oxatis_categorytype1: string | null;
    oxatis_oxatis_categorytype2: string | null;
    oxatis_oxatis_categorytype3: string | null;
    oxatis_oxatis_categoryid1: string | null;
    oxatis_oxatis_categoryid2: string | null;
    oxatis_oxatis_categoryid3: string | null;
    oxatis_oxatis_metatitle: string | null;
    oxatis_oxatis_metadescription: string | null;
    oxatis_oxatis_metakeywords: string | null;
    oxatis_oxatis_brand: string | null;
    mainintervener: string | null;
    intrastatnc8nomenclatureid: string | null;
    group1: string | null;
    group2: string | null;
    notprintable: boolean | null;
    notincluded: boolean | null;
    isfixedprice: boolean | null;
    noninvoiceabletype: number | null;
    componentcalculationtype: number | null;
    replacementitem: string | null;
    weightunitid: string | null;
    numberofitembypackage: number;
    volumeunitid: string | null;
    supplierid: string;
    ecotaxid: string | null;
    stockdestination: number;
    stockvarianceaccount: string;
    currentstockaccount: string;
    vatid: string;
    sysmoduleid: string | null;
    sysdatabaseid: string | null;
    sysrecordversion: number;
    sysrecordversionid: string;
    syseditcounter: number;
    limitdatesafetydelaymode: number | null;
    defaultlifetime: number | null;
    purchasepriceupdatetype: number | null;
    analyticaccounting_gridid: string | null;
    purchaseunitid: string | null;
    dimensionunitid: string | null;
    oxatis_oxatis_longdescription: string | null;
    oxatis_oxatis_longdescriptionclear: string | null;
    oxatis_oxatis_smallimage: string | null;
    purchasebillofquantitiesprogram_program: string | null;
    catalogid: string | null;
    catalogitemid: string | null;
    ecotaxfurnitureid: string | null;
    purchaseunitpriceprogram_program: string | null;
    localizablecaption_2: string | null;
    localizabledescom_2: string | null;
    localizabledescom_clear_2: string | null;
    localizablecaption_3: string | null;
    localizablecaption_4: string | null;
    localizablecaption_5: string | null;
    localizabledescom_3: string | null;
    localizabledescom_clear_3: string | null;
    localizabledescom_4: string | null;
    localizabledescom_clear_4: string | null;
    localizabledescom_5: string | null;
    localizabledescom_clear_5: string | null;
    intrastatorigincountryid: string | null;
    parentrangeitemid: string | null;
    rangetypeelementid0: string | null;
    rangetypeelementid1: string | null;
    rangetypeelementid2: string | null;
    rangetypeelementid3: string | null;
    rangetypeelementid4: string | null;
    defaultallowedstorehouseid: string | null;
    maintenancecontracttemplateid: string | null;
    guaranteetypeid: string | null;
    stockbillofquantitiesprogram_program: string | null;
    posthumbnail: string | null;
    giftvouchercashvalue: number | null;
    giftvouchervalidityduration: number | null;
    isextrafee: boolean;
    timeunitid: string | null;
    technicaldescom: string | null;
    technicaldescomclear: string | null;
    localizabletechnicaldescom_2: string | null;
    localizabletechnicaldescom_clear_2: string | null;
    localizabletechnicaldescom_3: string | null;
    localizabletechnicaldescom_clear_3: string | null;
    localizabletechnicaldescom_4: string | null;
    localizabletechnicaldescom_clear_4: string | null;
    localizabletechnicaldescom_5: string | null;
    localizabletechnicaldescom_clear_5: string | null;
    competenceid: string | null;
    equipmenttypeid: string | null;
    scheduleeventtemplateid: string | null;
    competencenumbertoplan: number | null;
    equipmenttypenumbertoplan: number | null;
    cadenceduration: number;
    cadencedurationtype: number;
    cadencedurationquantity: number;
    installationtime: number;
    labourcode: string | null;
    autoupdatelabourprice: boolean;
    isequipment: boolean;
    installationcalculationtype: number;
    materialprices_purchaseprice: number;
    materialprices_chargerate: number;
    materialprices_chargeamount: number;
    materialprices_costprice: number;
    materialprices_interestrate: number;
    materialprices_interestamount: number;
    materialprices_salepricevatexcluded: number;
    materialprices_brandrate: number;
    materialprices_vatid: string;
    materialprices_vatamount: number;
    materialprices_salepricevatincluded: number;
    materialprices_advisedsalepricevatexcluded: number;
    materialprices_setitemsalepricewithadvisedsaleprice: boolean;
    materialprices_isfixedprice: boolean | null;
    materialprices_ecotaxfurnitureid: string | null;
    labourprices_purchaseprice: number;
    labourprices_chargerate: number;
    labourprices_chargeamount: number;
    labourprices_costprice: number;
    labourprices_interestrate: number;
    labourprices_interestamount: number;
    labourprices_salepricevatexcluded: number;
    labourprices_brandrate: number;
    labourprices_vatid: string;
    labourprices_vatamount: number;
    labourprices_salepricevatincluded: number;
    labourprices_advisedsalepricevatexcluded: number;
    labourprices_setitemsalepricewithadvisedsaleprice: boolean;
    labourprices_isfixedprice: boolean | null;
    labourprices_ecotaxfurnitureid: string | null;
    canbepartiallyinvoiced: boolean;
    pickmovementdisallowedontotallybookeditem: boolean;
    salepricemodifieddate: string | null;
    salepricemodifieduserid: string | null;
    tarifeocode: string | null;
    tarifeofullcode: string | null;
    tarifeoproducerid: string | null;
    producername: string | null;
    tarifeopricedate: string | null;
    tarifeopriceversion: string | null;
    tarifeoupdatedatetime: string | null;
    issubscription: boolean;
    subscriptionpassings: number;
    subscriptiontotalcostprice: number;
    subscriptiontotalpurchaseprice: number;
    subscriptiontotalsalepricevatexcluded: number;
    subscriptionvalidityduration: number;
  
  }
  


  