export interface StockDocument {
    accountingexchangegroupid: null | string;
    constructionsiteid: null | string;
    createdfromconstructionsiteconsumptions: string;
    dealid: null | string;
    defaultactivateinventoryquantityformula: string;
    dispatchedbystorehouse: string;
    documentdate: string;
    documentnumber: string;
    documentstage: number;
    documenttype: number;
    executionquoteid: null | string;
    globaldocumentorder: number;
    groupingtype: null | string;
    hash_chainedid: null | string;
    hash_hash: null | string;
    id: string;
    incidentid: null | string;
    includesoldouttrackingnumbers: string;
    invoiceid: null | string;
    isexchangedocument: string;
    itemvaluetype: number;
    maintenancecontractid: null | string;
    modifiedsincerecovery: string;
    mustbetransferedtoaccounting: string;
    mustgetquantities: string;
    notes: null | string;
    notesclear: null | string;
    numberprefix: string;
    numbersuffix: string;
    origindocumentid: null | string;
    origindocumenttype: null | string;
    preparationstate: number;
    processdate: null | string;
    progressstatedocumentid: null | string;
    recoveredfrom: null | string;
    reference: null | string;
    removeoutofdatebestbeforestock: string;
    removeoutofdateusebystock: string;
    scheduleeventid: null | string;
    serialid: string;
    sortingtype: null | string;
    storehouseid: string;
    syscreateddate: string;
    syscreateduser: string;
    sysdatabaseid: null | string;
    syseditcounter: number;
    sysmodifieddate: string;
    sysmodifieduser: string;
    sysmoduleid: null | string;
    sysrecordversion: number;
    sysrecordversionid: string;
    targetstorehouseid: null | string;
    totalvolume: string;
    totalweight: string;
    transfereddocumentid: null | string;
    transitduration: null | string;
    transitenddate: null | string;
    transitstorehouseid: null | string;
    useadjustedlimitdate: string;
    usemaxprecisionforpump: string;
    validatestate: null | string;
    validationdate: null | string;
    validationglobaldocumentorder: null | string;
}

export interface StockDocumentLine  {

  billofquantitiesprogram_isactive: string;
  fixedquantity: string;
  booked: string;
  stockbookingallowed: string;
  toinvoice: string;
  targetlocation_multilocationmode: number;
  transitlocation_multilocationmode: number;
  phaselevel: number;
  updatecomponentsstockinfabrication: string;
  id: string;
  documentid: string;
  linetype: number;
  lineorder: number;
  isreferenceditem: string;
  quantity: string;
  realquantity: string;
  managestock: string;
  nomenclaturelevel: number;
  isprintable: number;
  quantitydecimalnumber: number;
  pricesdecimalnumber: number;
  ismanagedbycountermark: string;
  iscountermarkinitiated: string;
  volume: string;
  totalvolume: string;
  hastrackingdispatch: string;
  weight: string;
  totalweight: string;
  itemvalue: string;
  totalvalue: string;
  currentstock: string;
  newtotalvalue: string;
  accountingnewtotalvalue: string;
  existingtrackingnumber: string;
  trackingmasterline: string;
  previoustotalvalue: string;
  location_multilocationmode: number;
  mustprocessoriginquantity: string;
  dealid: string | null;
  transitlocation_locationid: string | null;
  gap: string;
  justificationquantity1: string;
  justificationquantity2: string;
  justificationquantity3: string;
  justificationquantity4: string;
  justificationquantity5: string;
  targetstorehouseid: string | null;
  receivedquantity: string | null;
  targetstockmovementid: string | null;
  stockchargeamount: string | null;
  gapstockmovementid: string | null;
  originlineid: string | null;
  remainingquantity: string | null;
  targetquantity: string | null;
  transitinputstockmovementid: string | null;
  transitoutputstockmovementid: string | null;
  locationcaption: string | null;
  unitcaption: string | null;
  commentary: string | null;
  newpump: string;
  currentpump: string;
  weightunitid: string | null;
  limitdate: string | null;
  volumeunitid: string | null;
  trackingnumber: string | null;
  unitid: string | null;
  storehouseid: string;
  stockmovementid: number;
  description: string;
  descriptionclear: string;
  itemid: string;
  parentlineid: string | null;
  topparentlineid: string | null;
  syscreateddate: string;
  syscreateduser: string;
  sysmodifieddate: string;
  sysmodifieduser: string;
  location_locationid: string | null;
  targetlocation_locationid: string | null;
  rangeitemid: string | null;
  maintenancecontractid: string | null;
  guaranteetypeid: string | null;
  incidentid: string | null;
  invoicelineid: string | null;
  customerproductid: string | null;
  billofquantitiesprogram_program: string | null;
  technicaldescription: string | null;
  technicaldescriptionclear: string | null;
  executionquotelineid: string | null;
  progressdocumentlineid: string | null;
}

export interface Storehouse {
  address_address1: string;
  address_address2: string;
  address_address3: string | null;
  address_address4: string | null;
  address_city: string;
  address_countryisocode: string;
  address_latitude: number | null;
  address_longitude: number | null;
  address_state: string;
  address_zipcode: string;
  asleep: string;
  caption: string;
  contact_cellphone: string | null;
  contact_civility: string | null;
  contact_email: string | null;
  contact_fax: string | null;
  contact_firstname: string | null;
  contact_name: string | null;
  contact_phone: string | null;
  id: string;
  lastinventorydate: string;
  main: string;
  multilocationdefaultmode: number;
  multilocationenabled: string;
  notes: string | null;
  notesclear: string | null;
  syscreateddate: string;
  syscreateduser: string;
  syseditcounter: number;
  sysmodifieddate: string;
  sysmodifieduser: string;
  type: number;
}